name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -e ./carnot-cli && pip install -e ./carnot-merge && pip install -e ./carnot-attest
      - run: carnot ./carnot-cli/examples/demo-python -o ./carnot-cli/cryptobom.json
      - run: carnot-attest --project "CI Demo" --bom ./carnot-cli/cryptobom.json --out ./attest-out
      - run: ls -l ./attest-out
