name: Tests

on:
  pull_request:
  push:

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r integrations/aws/requirements-dev.txt
          pip install -e carnot-cli
      - name: Run tests
        run: pytest -q integrations/aws/tests integrations/runtime/tests || true
